### ISSUE TITLE
Test convergence for capped AAs mutation

### ISSUE THREAD

**Issue by ijpulidos** [OpenFreeEnergy/feflow#79]
We want to check convergence of the following cases for protein mutation protocols. These should probably run in our GPU CI instances.

* Capped AA tests:
    * ALA -> GLY and GLY -> ALA 
    * Charged capped AA tests: LEU -> ASP and ASP -> LEU
* Convergence test: Adapt ALA dipeptide perses test case to feflow.

**Comment by jameseastwood** [comment]
@atravitz please look into the GPU runner token. Ethan Holtz may be able to help.

**Comment by ijpulidos** [comment]
Solved by #95
