### ISSUE TITLE
`NonEquilibriumCyclingProtocol` does not expect multiple atom mappings

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/feflow#89]
When testing the `NonEquilibriumCyclingProtocol` in production via alchemiscale we hit the following error:
> Task:
Task-82715a31c4744b3bbe2260ee64a1285d-asap-public-tyk2_neq_testing
Error:
('AttributeError', ("'list' object has no attribute 'componentA'",))
Traceback:
Traceback (most recent call last):
  File "/lila/home/dotson/mambaforge/envs/alchemiscalemiscale-compute-ddotson-v0.5.0-2024.08.15/lib/python3.12/site-packages/gufe/protocols/protocolunit.py", line 320, in execute
    outputs = self._execute(context, **inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lila/home/dotson/mambaforge/envs/alchemiscalemiscale-compute-ddotson-v0.5.0-2024.08.15/lib/python3.12/site-packages/feflow/protocols/nonequilibrium_cycling.py", line 194, in _execute
    ligand_a = ligand_mapping.componentA
               ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'componentA'

This seems to be due to the protocol not handling the case where a list of mappings are passed to the `_create` function which should be expected going from the [base class type hint](https://github.com/OpenFreeEnergy/gufe/blob/a6036901d5d33bdfe9b6fd197f1a3218b80ff990/gufe/protocols/protocol.py#L144) and the hybrid topology protocol which handles the case of a [list of mappings](https://github.com/OpenFreeEnergy/openfe/blob/f4475bfe47fa53614cf22ba7e7662a6cf288ba4b/openfe/protocols/openmm_rfe/equil_rfe_methods.py#L523).

**Comment by IAlibay** [comment]
Whilst the equilibrium protocol does handle a list a mappings more gracefully, it will also reject a mapping of length > 1. That's done elsewhere under mapping validation: https://github.com/OpenFreeEnergy/openfe/blob/f4475bfe47fa53614cf22ba7e7662a6cf288ba4b/openfe/protocols/openmm_rfe/equil_rfe_methods.py#L210

Is there a reason why folks are trying to pass through multiple mappings? As far as I'm aware the tooling just isn't made for this.

Ideally the cleaning up of the setupunit (to more gracefully handle all this), should happen when we merge the two protocols (i.e. there's no point cleaning early if we're going to merge things together later).
